### ISSUE TITLE
[RFC] `--pdb`: Friendlier default (use warning and infer `--reruns 0`)

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest-rerunfailures#248]
Assume `pyproject.toml`:

```toml
[tool.pytest.ini_options]
addopts = "--reruns 2"
```

# Current behavior

Right now, passing `--pdb` will raise:

```
ERROR: --reruns incompatible with --pdb
```

# Better: Assume `--reruns 0` if `--pdb`

It's highly unlikely a person attempting to drop into a shell wants reruns. Rather than error, show a warning:

`WARNING: --reruns incompatible with --pdb, --reruns will behave as if set to 0`
