### ISSUE TITLE
[RFC] `--reruns-on-exitfirst`: set reruns with `--exitfirst` / `-x`

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest-rerunfailures#249]
Assume `pyproject.toml`:

```toml
[tool.pytest.ini_options]
addopts = "--reruns 2"
```

# Current behavior

Right now, passing `--exitfirst` / `-x` will rerun twice.

# Better: `--reruns-on-exitfirst 0`

This way, the user can set the reruns with `exitfirst` is used so it instantly errors. It preserves the default behavior.

`--exitfirst`'s docs:

```
  -x, --exitfirst       Exit instantly on first error or failed test
```
